# Generated by Django 3.2.7 on 2021-10-13 22:48

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211004_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Only UCA accounts allowed', max_length=254, unique=True, validators=[django.core.validators.RegexValidator(re.compile('\\w+@uca\\.edu\\.ar'), 'Enter a valid email.', 'invalid')], verbose_name='email address'),
        ),
    ]
