# Generated by Django 3.2.7 on 2022-04-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicle',
        ),
    ]
