# Generated by Django 3.2.7 on 2022-05-16 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hovlane_hovmilestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hovlane',
            options={'verbose_name': 'Carril HOV', 'verbose_name_plural': 'Carriles HOV'},
        ),
        migrations.AlterModelOptions(
            name='hovmilestone',
            options={'verbose_name': 'Milestone HOV', 'verbose_name_plural': 'Milestones HOV'},
        ),
        migrations.AlterField(
            model_name='hovlane',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='hovlane',
            name='is_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='hovlane',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hovlane',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='hovmilestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='hovmilestone',
            name='id_HovLane',
            field=models.ForeignKey(db_column='id_HovLane', on_delete=django.db.models.deletion.CASCADE, to='core.hovlane', verbose_name='Carril HOV'),
        ),
        migrations.AlterField(
            model_name='hovmilestone',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='hovmilestone',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='hovmilestone',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='hovmilestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterModelTable(
            name='hovlane',
            table='hov_lane',
        ),
        migrations.AlterModelTable(
            name='hovmilestone',
            table='hov_milestone',
        ),
    ]
